signing_key = "21R4uDwS7fdxsNPWy92DArC575sYiQdEasFBVEpH8m53e"
dh_key = "DRYKr9pHPf6i6QmQiAihrQnEqEYXg96fe5kyMiCrBUJP"
dkg_enc_key = "6Uzern4hX1a2VJmWmHMavmUgeXmNDrxsC4JpCRB49dXk7tRK5QwXtuTUw8sUpGpGkc"
address = "127.0.0.1:8020"
batchposter = "127.0.0.1:8025"
