apikey = "sEVxPYlY3Rwte9ZApZDZPd-K7TCiZnBlhZp7se8jVWM="

[net]
bind = "11.0.0.3:8000"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "Fg3tVVbB4UX5cTcqicFkk1ApbUJ71zq9m86ffiBHerTn"
public = "21R4uDwS7fdxsNPWy92DArC575sYiQdEasFBVEpH8m53e"

[keys.dh]
secret = "221uwQa7dhYyzwwVQcBF4TAkmyjEcZ5egbrtUN5P3uKq"
public = "DRYKr9pHPf6i6QmQiAihrQnEqEYXg96fe5kyMiCrBUJP"

[keys.dkg]
secret = "4egxEWyRd5SEG3hoDuCcon1z822oFEXeiEdjnn4VgFyN"
public = "6Uzern4hX1a2VJmWmHMavmUgeXmNDrxsC4JpCRB49dXk7tRK5QwXtuTUw8sUpGpGkc"

[chain]
id = 31337
rpc-url = "http://11.0.1.0:8545/"
websocket-url = "ws://11.0.1.0:8545/"
key-management-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"
auction-contract = "0x1a642f0e3c3af545e7acbd38b07251b3990914f1"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
