id = 0
effective_timestamp = "2025-09-01T02:00:00Z"

[[members]]
node = "node_0"
signing_key = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"
dh_key = "AZrLbV37HAGhBWh49JHzup6Wfpu2AAGWGJJnxCDJibiY"
dkg_enc_key = "7PdmfTS45d2hTXB8NcrTmvDwUVBimpYBbrBaGnu3i5Ne65krVfUpbe7bYRHS3AEg7H"
address = "11.0.0.1:8000"
http_api = "11.0.0.1:8004"
grpc_api = "11.0.0.1:8003"
batch_poster_api = "127.0.0.1:8547"
sig_key_address = "0x647ff873518108c6ae1e3b310bb6d68c72d369ab"

[[members]]
node = "node_1"
signing_key = "vGKKAxVNfkSCdn8qh36nXdSZqyhPq644sQBoeZtcEUCR"
dh_key = "FHTJAk6oyt3jefEp1ZrPEn2MkqRt2LibEFd57AnEUZdb"
dkg_enc_key = "7p1BtEz7WnFMt6Hr28X3Rngqza6i8hRoswhzZRFd6GzgkspLKHBfDocHP8DwzXiNiZ"
address = "11.0.0.2:8000"
http_api = "11.0.0.2:8004"
grpc_api = "11.0.0.2:8003"
batch_poster_api = "127.0.0.2:8547"
sig_key_address = "0xd3ab3e193f9c438100f6aefa164a214b5be55379"

[[members]]
node = "node_2"
signing_key = "264jMLf85hfufg4ck97Hw2jiL6i1PHNoGUqxUqfhtssaE"
dh_key = "63eYNKoW2PsWZFhHHj3eZwHTdPE7gEjEDM7gGeDf9Uaj"
dkg_enc_key = "62bnAAbU58zZUcGqy9JKGZRZHkm3g7JZB2DtJGQyChXQBPGvXSS6fF21yoxiVuD1eb"
address = "11.0.0.3:8000"
http_api = "11.0.0.3:8004"
grpc_api = "11.0.0.3:8003"
batch_poster_api = "127.0.0.3:8547"
sig_key_address = "0x92be0a723a8cf1c2e74c5c5ebd57625fd7b26bc5"

[[members]]
node = "node_3"
signing_key = "v6UBdLT5BvMhLW7iKv7M2xYeaW2SCAsnZ5PiSg6AaKfA"
dh_key = "Do2GmAexW5MUdD8nToDiBWGbDgk1AwXoxtLTyirDtKQh"
dkg_enc_key = "7aZBFZUEbXxFH9SiGJeUyjzas4mYJ1R13mTPsPeawVU7JFuocfvX9XsRT8qgr17RCe"
address = "11.0.0.4:8000"
http_api = "11.0.0.4:8004"
grpc_api = "11.0.0.4:8003"
batch_poster_api = "127.0.0.4:8547"
sig_key_address = "0xa064549353fafd38f1000627acc581c9354b1cbe"

[[members]]
node = "node_4"
signing_key = "tV66KknkDH47hRSNzwJtt7Q7EZtxVxQsNnUGoAJdDn6J"
dh_key = "HXaesvEGFiDgrVTix1fKzSLTarFexTZSJD6ymSrF7vPL"
dkg_enc_key = "6R69TzDg3jo1MTex9Uter9XQud458YPpSvXirkYdS295PV81CRvgz5jVWQbkCpZnYV"
address = "11.0.0.5:8000"
http_api = "11.0.0.5:8004"
grpc_api = "11.0.0.5:8003"
batch_poster_api = "127.0.0.5:8547"
sig_key_address = "0x9bfc8551ffd3a21f856490870f111051b1ef39ab"

[[members]]
node = "node_5"
signing_key = "hcUWjmK8pTz5AY39CDh1gVnVbaF4nNuEf2dQ5SWXZQyh"
dh_key = "95KhKesfhSgMubqtjv8f13d6XosWFME4Ya33LH9jkX23"
dkg_enc_key = "64NhDL71i1ZCyWiZtvq14Kpqg9LGRvWJwVZJbjUBmcMFBQSy7AVFZNF55ueoZE3ZGw"
address = "11.0.0.6:8000"
http_api = "11.0.0.6:8004"
grpc_api = "11.0.0.6:8003"
batch_poster_api = "127.0.0.6:8547"
sig_key_address = "0x606ee0e5bec54a76896725dd6befad90eb7b9555"

[[members]]
node = "node_6"
signing_key = "ufyeJDrHnH7BuuBvwaonu86YYZKYW47VedCdZ2yqAanm"
dh_key = "ER5CSn1QjRZ6rJ2d3m6HSyyDoLDr4ab29GkfVhNf3Eoo"
dkg_enc_key = "79ognYKwJeTywbsSo45F6q6m8d4qovewLZ789N5UMknGq4XuKMhLs5TWcdDDFBhkbc"
address = "11.0.0.7:8000"
http_api = "11.0.0.7:8004"
grpc_api = "11.0.0.7:8003"
batch_poster_api = "127.0.0.7:8547"
sig_key_address = "0xcb8496f5f267b6f68879ab9f3b798d3b1851efed"

[[members]]
node = "node_7"
signing_key = "24hzR236zciuEFgtq7n2uHhoJBYkHDtd2s8LCCURLRfvU"
dh_key = "4FmHYY46oj2kwzm5Ddyvd4hQHHWMgwPmLMbzgBNHcfiD"
dkg_enc_key = "73SVs6cBCbUpARTw6UBuQnetXWw67F4RTVD3d1RuyJXZ49TWfiuvaf9BZAZAe6kdFD"
address = "11.0.0.8:8000"
http_api = "11.0.0.8:8004"
grpc_api = "11.0.0.8:8003"
batch_poster_api = "127.0.0.8:8547"
sig_key_address = "0xdade452b38c5c895c6bb8f47dfc11c6f9b1fcde4"

[[members]]
node = "node_8"
signing_key = "fkTFXcMaEEzutGCreYpDb1B2h8hNMf6UMNRbt8dnhi2v"
dh_key = "vzvao6vfQtWpBJvPsVCk9FL7RsJBNE4W8SvNWtofxqB"
dkg_enc_key = "5zhvUH7JXkViZ6FTRocX6TTUbC83x7n9cAkL8TeNi8cuMazhTESU4QvGQJrunbzwgd"
address = "11.0.0.9:8000"
http_api = "11.0.0.9:8004"
grpc_api = "11.0.0.9:8003"
batch_poster_api = "127.0.0.9:8547"
sig_key_address = "0x0ff7e0cf31a850160284c4d477ca394828a9ef90"

[[members]]
node = "node_9"
signing_key = "28NkSnRnefwgwoP5Xj1Xo21bAHpVQcYEYouTNyjyjH5V3"
dh_key = "69BWDWEuKYvsF9EfCjDYJpxrNpSymvX23o3JHxQxhVfQ"
dkg_enc_key = "7jUogxWxRhXuaRsfPcA3g8eLbLCu5MgJBW66qz8oi4dvy6zm9aewDDK1HgNMqSuGXE"
address = "11.0.0.10:8000"
http_api = "11.0.0.10:8004"
grpc_api = "11.0.0.10:8003"
batch_poster_api = "127.0.0.10:8547"
sig_key_address = "0xdb92b43a905573378051147d55b11ca272ba3e44"

[[members]]
node = "node_10"
signing_key = "pzFeUaH8Q73zYiJKJNgf86BGH99TtTH5wXJLUXCkJ3Es"
dh_key = "EBPENaYdA28xAV7cHh6q1ESJcsf7P2LpZUWv5dEmo2Sv"
dkg_enc_key = "6yKj81Wuj6eBuMT5jmUu3HGX9AvvX3njQFaZXJoKX9CjmsSJNDMoQJTPA5M9ug1hpr"
address = "11.0.0.11:8000"
http_api = "11.0.0.11:8004"
grpc_api = "11.0.0.11:8003"
batch_poster_api = "127.0.0.11:8547"
sig_key_address = "0x139cd4216e8a2ea43c1276f6003cc9a87941c01f"

[[members]]
node = "node_11"
signing_key = "iNJBiPwwdA53Gds2rnJnSm1sjvnR8Ep72LZKf8fxVo2e"
dh_key = "D2dCHzbNYVo18z9yH4KnuiRbGMj3qxxRLAGwFEUrBUM3"
dkg_enc_key = "6EGHKHhBh984R4CV9F7g7oHDvQrFisoAk8onZqUnUj1UwQd38hzVxgVZRW7n4aDCdo"
address = "11.0.0.12:8000"
http_api = "11.0.0.12:8004"
grpc_api = "11.0.0.12:8003"
batch_poster_api = "127.0.0.12:8547"
sig_key_address = "0x501fe8a4554ab753c88cfc2079da72a4a8bf7624"

[[members]]
node = "node_12"
signing_key = "op7c28pHtcAH3qtKVAPz8amCfs7mcctxeM5ztJKURmzJ"
dh_key = "HBen32g4EtpoyA4hUWeqmHybw52xPWrkJapvHDo45AQi"
dkg_enc_key = "6J3F9RJRQ25S5YogAxZTNuQF9Bo2gEmE49XNsp9HYZTrZPnQ818jVU7Vrz4U1nA1Ck"
address = "11.0.0.13:8000"
http_api = "11.0.0.13:8004"
grpc_api = "11.0.0.13:8003"
batch_poster_api = "127.0.0.13:8547"
sig_key_address = "0x91e339459ff6a9667f5f46b63952d34c1e84bbb0"

[[members]]
node = "node_13"
signing_key = "26zcQ6VfgK5eS9ABtaAg4roUfivEbEVBJFDsZgML8tbxy"
dh_key = "Gq1X8StampJTD9awjR8q9JNQCdKCeNFi5ygvNwHdj1fB"
dkg_enc_key = "5iy9bTMYGTPRkduRs8wDWj6eoMMgVtHAD4aaStV4VtJqXSARpcQN5zdSzaSv6dCYSR"
address = "11.0.0.14:8000"
http_api = "11.0.0.14:8004"
grpc_api = "11.0.0.14:8003"
batch_poster_api = "127.0.0.14:8547"
sig_key_address = "0x7b244c795c341c73df1430897fa1b1a7e6638e83"

[[members]]
node = "node_14"
signing_key = "u8fkqXA2EnDaAqFbsHew42D5JzHkeM46cLa7UdxYqjHe"
dh_key = "2XzjVcuXuxyjDiZvYU6BJ4JJjM5hb348MTUB44onskxC"
dkg_enc_key = "61kqNbMn1nadgjqnCSf3KDFNdCvMWAYvmARn1z6zusFupgUrYB9DWmp2H29ukoEfsr"
address = "11.0.0.15:8000"
http_api = "11.0.0.15:8004"
grpc_api = "11.0.0.15:8003"
batch_poster_api = "127.0.0.15:8547"
sig_key_address = "0x30f7a4d4374c6fdfc5d8757a889d2bfbac97edbf"
