stamp = "/tmp/timeboost.hcUWjmK8pTz5AY39CDh1gVnVbaF4nNuEf2dQ5SWXZQyh.stamp"

[net]
bind = "11.0.0.6:8000"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "6YJc9asDJQsFFHHg8iX23oL1sySx2EgTGM8CqDd71WMa"
public = "hcUWjmK8pTz5AY39CDh1gVnVbaF4nNuEf2dQ5SWXZQyh"

[keys.dh]
secret = "Ho9ZZCkP1i6f12fkWGUZucJxX2qbv9L3UbB56sqwjvkw"
public = "95KhKesfhSgMubqtjv8f13d6XosWFME4Ya33LH9jkX23"

[keys.dkg]
secret = "38Fikb4yktatpnV1DHevSzwquhnMaLHJqbGiMkWjvWj4"
public = "64NhDL71i1ZCyWiZtvq14Kpqg9LGRvWJwVZJbjUBmcMFBQSy7AVFZNF55ueoZE3ZGw"

[chain]
id = 31337
rpc-url = "http://11.0.1.0:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
