stamp = "/tmp/timeboost.i5ccK9sZFtdWpB6rp4deJKvb8UNMCYhxj7G2sGBAsdam.stamp"

[net]
bind = "11.0.0.5:8000"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "AjaQA4tfSzm8mz7crQNZLzAsa99FXLnLarUX8p65PCUf"
public = "i5ccK9sZFtdWpB6rp4deJKvb8UNMCYhxj7G2sGBAsdam"

[keys.dh]
secret = "F4TUCvytZyTPVk2qvZAXp9MwWKBEwFMxDeNrTusoTgN1"
public = "6czLW5NW4C74eQUBdzwHGmUzA5B8vbWpuH6amZHXtPnq"

[keys.dkg]
secret = "AWUnMQ6wp6k6njVMu8TSfGgwnMZhYw82p1KdUCqXGKhx"
public = "7N4Bm2ssVuq9WVZj5i9iHwWRcGwea86J13fqvwdEnFasEfREsZLViMFEJxfd5JrVsc"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
