committee = 0
stamp = "/tmp/timeboost.6.stamp"

[net]
bind = "11.0.0.7:8000"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "6NZdk8EGRSVS7sSjcjMiC8vL4KcSY41ELU6HaKyk1Drk"
public = "ufyeJDrHnH7BuuBvwaonu86YYZKYW47VedCdZ2yqAanm"

[keys.dh]
secret = "F5E9cp5qUe4z2wdaRYvEhFMYXaLy4sEX1rwCWRcTH69i"
public = "ER5CSn1QjRZ6rJ2d3m6HSyyDoLDr4ab29GkfVhNf3Eoo"

[keys.dkg]
secret = "Aj5vDyhADSmkZxDpREw2Re6qxDgDw4tXyKGhiKToTBsX"
public = "79ognYKwJeTywbsSo45F6q6m8d4qovewLZ789N5UMknGq4XuKMhLs5TWcdDDFBhkbc"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://11.0.1.0:8545/"
ws-url = "ws://11.0.1.0:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
