committee = 0
stamp = "/tmp/timeboost.13.stamp"

[net]
bind = "11.0.0.14:8000"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "H7X14ZNMDxwDrkKw1HhaoqEsSv7L9C18dfkbQbUSYFWD"
public = "26zcQ6VfgK5eS9ABtaAg4roUfivEbEVBJFDsZgML8tbxy"

[keys.dh]
secret = "DiRBsajPr8AbZMmsNNzEYP84bgeYQeaKn5qP7d4YBry"
public = "Gq1X8StampJTD9awjR8q9JNQCdKCeNFi5ygvNwHdj1fB"

[keys.dkg]
secret = "GNAFDoD7z6wBNXeMfd4BvqMNyrVB4u7cr7MCSr1uV662"
public = "5iy9bTMYGTPRkduRs8wDWj6eoMMgVtHAD4aaStV4VtJqXSARpcQN5zdSzaSv6dCYSR"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://11.0.1.0:8545/"
ws-url = "ws://11.0.1.0:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
