committee = 0
stamp = "/tmp/timeboost.7.stamp"

[net]
bind = "11.0.0.8:8000"
batch_poster_api = "127.0.0.8:8547"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "AMJEYXVhS4FfoqfD6VL5nZTNbzJQdtgdxBcVEAwZnLJ3"
public = "24hzR236zciuEFgtq7n2uHhoJBYkHDtd2s8LCCURLRfvU"

[keys.dh]
secret = "5zhwDWJ1ut6q871aHCHmH7QRCHDykXjUSEriGTLkwezL"
public = "4FmHYY46oj2kwzm5Ddyvd4hQHHWMgwPmLMbzgBNHcfiD"

[keys.dkg]
secret = "7FHMi3eLRRSdcwtnn4pwGvGLWHf3JpmVXjqyPyFkDy51"
public = "73SVs6cBCbUpARTw6UBuQnetXWw67F4RTVD3d1RuyJXZ49TWfiuvaf9BZAZAe6kdFD"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://11.0.1.0:8545/"
ws-url = "ws://11.0.1.0:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
