stamp = "/tmp/timeboost.pG9cBbvmj7qqCAVKR9EKefwYrHX8c4y1go891CVCPw1W.stamp"

[net]
bind = "11.0.0.12:8000"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "5N8kSoP4zvGo4TfZxWHQMTbthcWFSehPCPueQbZxKRBD"
public = "pG9cBbvmj7qqCAVKR9EKefwYrHX8c4y1go891CVCPw1W"

[keys.dh]
secret = "4gyBDPfxePdhKSZpRQCpA97VobTg3wiUhzYAGtTfVhXS"
public = "BPuD53onChfNdaAQkkqeKDWj2RvmJywoMehuamSBidSx"

[keys.dkg]
secret = "CC6bf85AB7Jjbtdzt5bZ2D3f5evJdV4Edkmih6ZPE8tt"
public = "5uz43rVdxMeLPoRtgAY74NuALzv7XoCzPSyeNpfopaev4HWtA17B7wWHFxkL8zHfzv"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
