stamp = "/tmp/timeboost.tiLaXi4xvFAK2GcUdjbDxWpJKq3kceqgJXTkKjGhduEJ.stamp"

[net]
bind = "11.0.0.15:8000"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "53X3PTCYNNc3FsSiJX1GCDxPmw3k4sfh4jVSF8pR45z"
public = "tiLaXi4xvFAK2GcUdjbDxWpJKq3kceqgJXTkKjGhduEJ"

[keys.dh]
secret = "4zMVo2A4ZfqF2pymNz3xPMJjoMWitVywrTntdgGyL4UU"
public = "2179bYS7qukTLacc3Wz5mS5oFJnUKzNmrFAMwwUGn7B5"

[keys.dkg]
secret = "9m2Ugq6mqKcCdjxXXoai2XRxt7hq48p2tmpnGstUR5Zr"
public = "6MFv9guPANDGQ9gnzXhWdPW29nTsYqXodgtE1hV7JhDjSRjiuaM4AESb4uW2Pc74DR"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
