stamp = "/tmp/timeboost.u8fkqXA2EnDaAqFbsHew42D5JzHkeM46cLa7UdxYqjHe.stamp"

[net]
bind = "11.0.0.15:8000"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "4CfwWmEj3BdHvTxrENqwRe9G3qHWWMcVDxv4zTBYkuMn"
public = "u8fkqXA2EnDaAqFbsHew42D5JzHkeM46cLa7UdxYqjHe"

[keys.dh]
secret = "BxVvF1QFrvM8bUKEfeFnMt23mWMcUq8wtgCkJr9hWTbE"
public = "2XzjVcuXuxyjDiZvYU6BJ4JJjM5hb348MTUB44onskxC"

[keys.dkg]
secret = "GdaxocRNFeGaAZWiX9PQ3zYS7eH4u9X3u2bCHxXyS9PC"
public = "61kqNbMn1nadgjqnCSf3KDFNdCvMWAYvmARn1z6zusFupgUrYB9DWmp2H29ukoEfsr"

[chain]
id = 31337
rpc-url = "http://11.0.1.0:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
