stamp = "/tmp/timeboost.wzaREUZTT8gGNhtnHcdcqbrJVoEi8tQt8XLZyWDretYm.stamp"

[net]
bind = "11.0.0.11:8000"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "4Th9nd7dgUBKQUiTrVDxsd513W2r4PfyJv4YQbVPRnXx"
public = "wzaREUZTT8gGNhtnHcdcqbrJVoEi8tQt8XLZyWDretYm"

[keys.dh]
secret = "2HDMqk274Ed5dC3nEB4Fp9BHN7Njds9RD713TomP5ERj"
public = "Frmtaafy1HBFNCo2CNa5HuMK7psE3zeYn3io1FfUibKs"

[keys.dkg]
secret = "GcPfrWuoSGHf2E15oBjx55pSM3TSvV43Bg1DgFa1ukQH"
public = "6Zyn8o7Uws4Z9LAYH2C4P1fvkszEm9D65pJY5BSAUF5BxWRVGnwhDTYfwr8K3cXCcX"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
