id = 31337
rpc-url = "http://11.0.1.0:8545/"
websocket-url = "ws://11.0.1.0:8545/"
key-management-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"
auction-contract = "0x1a642f0E3c3aF545E7AcBD38b07251B3990914F1"
