stamp = "/tmp/timeboost.23oAdU4acQbwSuC6aTEXqwkvQRVCjySzX18JfBNEbHgij.stamp"

[net]
bind = "127.0.0.1:8060"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "3w2vnSTfFsWXeNfRhS9TfZm5rptKmdgZPQUAvb2PaqRU"
public = "23oAdU4acQbwSuC6aTEXqwkvQRVCjySzX18JfBNEbHgij"

[keys.dh]
secret = "H7ifD5bqkEdPbHTss5VHfZ64jTQr9si6WsgTxvMQAphA"
public = "B65CLdoYGSRtXRR4YU2wqzpqrwcd4KHiQqgaW5ShnoY6"

[keys.dkg]
secret = "5Fwo9VHphxfWK3vT5zTWsKaZRzXSgHYn3XZL5rQdRU4s"
public = "7KgCqy1taizFPX2v5CvZit8HDnNPQF2M7EbHHy24a3banaKkqeqye6kM4apnbjZMhd"

[committee.contract]
rpc-url = "http://127.0.0.1:8545/"
websocket-url = "ws://127.0.0.1:8545/"
address = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[chain]
id = 31337
rpc-url = "http://127.0.0.1:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
