stamp = "/tmp/timeboost.h7qA6fzJMhYLotwxNRGGBEDqUkaNpCJ8cBeCGQuAumTq.stamp"

[net]
bind = "127.0.0.1:8050"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "8rNjkteTcKonpHTGoQYNihfkd7YgAfWRixLKTXatsLq9"
public = "h7qA6fzJMhYLotwxNRGGBEDqUkaNpCJ8cBeCGQuAumTq"

[keys.dh]
secret = "DTYobbJujfpvhLSyEWe5AmqEb22LwzJoHPNhLVaRXcBK"
public = "HXD3TRTQ2cK8oGbEWmhnRdwFa96wBPc1mntVt7wt98mK"

[keys.dkg]
secret = "7zEj9Tq2NjbUeMoqLMYBwjmTwjUMoVTFkqztfL9TdHmN"
public = "78HGPt9ceH5TMn5rB9LUdxkY9pofXE8RPo4WckmyqSicnweQ4Ue5DJ6dTDQ1ptLwfz"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
