apikey = "sEVxPYlY3Rwte9ZApZDZPd-K7TCiZnBlhZp7se8jVWM="

[net]
bind = "127.0.0.1:8050"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "8rNjkteTcKonpHTGoQYNihfkd7YgAfWRixLKTXatsLq9"
public = "h7qA6fzJMhYLotwxNRGGBEDqUkaNpCJ8cBeCGQuAumTq"

[keys.dh]
secret = "DTYobbJujfpvhLSyEWe5AmqEb22LwzJoHPNhLVaRXcBK"
public = "HXD3TRTQ2cK8oGbEWmhnRdwFa96wBPc1mntVt7wt98mK"

[keys.dkg]
secret = "7zEj9Tq2NjbUeMoqLMYBwjmTwjUMoVTFkqztfL9TdHmN"
public = "78HGPt9ceH5TMn5rB9LUdxkY9pofXE8RPo4WckmyqSicnweQ4Ue5DJ6dTDQ1ptLwfz"

[chain]
id = 31337
rpc-url = "http://127.0.0.1:8545/"
websocket-url = "ws://127.0.0.1:8545/"
key-management-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"
auction-contract = "0x1a642f0e3c3af545e7acbd38b07251b3990914f1"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
