stamp = "/tmp/timeboost.mjL4pJF2jqy4TAht8UveAF9H7xUYYyP16aDH6Rnu8Zi8.stamp"

[net]
bind = "127.0.0.1:8130"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "8ctic7ZqgQ8VP5U9DKNDcemyM4CmzFsGsJduqPekfcwj"
public = "mjL4pJF2jqy4TAht8UveAF9H7xUYYyP16aDH6Rnu8Zi8"

[keys.dh]
secret = "HgTF9vgrnua9xWhspKiDE9vQGuzyhmGMQJY2JFnD2hrY"
public = "EJ3ZpDXbmD9Ma1rRLY8LVGuNGjiskuGmnyzNZWXyQvRa"

[keys.dkg]
secret = "9aVdLRQM4sYKeXHqt6kNALFQyvAUQ9tXDnwMtwtzHie2"
public = "5kA6kUeAuqVYRcUugGkngV2DJSpDDJTxzGmZdiNEsWonp5yW9oYLNJQB3n6Niyw6PW"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
