stamp = "/tmp/timeboost.pBxmET1WX6b1cFpEsoHKBpn8mcQavX3dh8zotDUDjVi3.stamp"

[net]
bind = "127.0.0.1:8080"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "G816aQnTqDJj2T3cQdmgoJkhS8HgbPgfnQx6HMPeMFuq"
public = "pBxmET1WX6b1cFpEsoHKBpn8mcQavX3dh8zotDUDjVi3"

[keys.dh]
secret = "GKcFJP1fLCbFKqgStG8NrEX11hPPT2nA75YanrcRV2eH"
public = "8xfUWVGNLTct1dT8ThvpU4zW2nExXM3PRYSjtbkMuVUr"

[keys.dkg]
secret = "fk98YvHm1R8rW1K9nuJwY6RbhkDaLhc2jAU9oA65b3B"
public = "6xS6YrT3WUzB84ujo6YamrcN8TVVTq9naV5WxzsV8pdjnJ1NLB2pxjrFUDrs13N9nQ"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
