signing_key = "pBxmET1WX6b1cFpEsoHKBpn8mcQavX3dh8zotDUDjVi3"
dh_key = "8xfUWVGNLTct1dT8ThvpU4zW2nExXM3PRYSjtbkMuVUr"
dkg_enc_key = "6xS6YrT3WUzB84ujo6YamrcN8TVVTq9naV5WxzsV8pdjnJ1NLB2pxjrFUDrs13N9nQ"
address = "127.0.0.1:8080"
batchposter = "127.0.0.1:8085"
