stamp = "/tmp/timeboost.pG9cBbvmj7qqCAVKR9EKefwYrHX8c4y1go891CVCPw1W.stamp"

[net]
bind = "127.0.0.1:8110"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "5N8kSoP4zvGo4TfZxWHQMTbthcWFSehPCPueQbZxKRBD"
public = "pG9cBbvmj7qqCAVKR9EKefwYrHX8c4y1go891CVCPw1W"

[keys.dh]
secret = "4gyBDPfxePdhKSZpRQCpA97VobTg3wiUhzYAGtTfVhXS"
public = "BPuD53onChfNdaAQkkqeKDWj2RvmJywoMehuamSBidSx"

[keys.dkg]
secret = "CC6bf85AB7Jjbtdzt5bZ2D3f5evJdV4Edkmih6ZPE8tt"
public = "5uz43rVdxMeLPoRtgAY74NuALzv7XoCzPSyeNpfopaev4HWtA17B7wWHFxkL8zHfzv"

[chain]
id = 31337
rpc-url = "http://127.0.0.1:8545/"
websocket-url = "ws://127.0.0.1:8545/"
key-management-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"
auction-contract = "0x5fcb496a31b7AE91e7c9078Ec662bd7A55cd3079"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
