stamp = "/tmp/timeboost.pzFeUaH8Q73zYiJKJNgf86BGH99TtTH5wXJLUXCkJ3Es.stamp"

[net]
bind = "127.0.0.1:8100"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "4DXdtKDNBs1DeLGP7GeqGWeSuX3RgkRhwcT9aXKwzu9p"
public = "pzFeUaH8Q73zYiJKJNgf86BGH99TtTH5wXJLUXCkJ3Es"

[keys.dh]
secret = "7X3bBjha3wEUGvCNUWf7627RTqpNFGo6uwUtHM1nFYrW"
public = "EBPENaYdA28xAV7cHh6q1ESJcsf7P2LpZUWv5dEmo2Sv"

[keys.dkg]
secret = "3hBZLhBJM3hmYzLrGy2AGijUcEvo6Wh1f2ej6KtHvNmX"
public = "6yKj81Wuj6eBuMT5jmUu3HGX9AvvX3njQFaZXJoKX9CjmsSJNDMoQJTPA5M9ug1hpr"

[chain]
id = 31337
rpc-url = "http://127.0.0.1:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
