stamp = "/tmp/timeboost.qh3tJ83Ko7f6B9ksPj8PPwTshFmToj9zbjcgPCegar7m.stamp"

[net]
bind = "127.0.0.1:8030"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "FvNPFm2VySb2hasVFSgRyzSjnDy73BDL7XJfRmGy4SST"
public = "qh3tJ83Ko7f6B9ksPj8PPwTshFmToj9zbjcgPCegar7m"

[keys.dh]
secret = "3SxqfGusCVtc6oujqVPtkwKdhbN1aUKMNQbbhZZoExNu"
public = "CetqwdEDC8BkBXB9wpTmuumCsj2kRPcq9hbJVEdaQ7r9"

[keys.dkg]
secret = "9F7mt5c8twcF3FBVWpHxN8gBM7ZLSTh2jtvkxtrJKF8Z"
public = "7DLbA7pdikS3BjBWyAPbDLivEEPXGU9anPngeTo8nyAsJFSoBvjD8UStzSp1MgBu8V"

[chain]
id = 31337
rpc-url = "http://127.0.0.1:8545/"
websocket-url = "ws://127.0.0.1:8545/"
key-management-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
