signing_key = "tiLaXi4xvFAK2GcUdjbDxWpJKq3kceqgJXTkKjGhduEJ"
dh_key = "2179bYS7qukTLacc3Wz5mS5oFJnUKzNmrFAMwwUGn7B5"
dkg_enc_key = "6MFv9guPANDGQ9gnzXhWdPW29nTsYqXodgtE1hV7JhDjSRjiuaM4AESb4uW2Pc74DR"
address = "127.0.0.1:8140"
batchposter = "127.0.0.1:8145"
