stamp = "/tmp/timeboost.vGKKAxVNfkSCdn8qh36nXdSZqyhPq644sQBoeZtcEUCR.stamp"

[net]
bind = "127.0.0.1:8010"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "FWJzNGvEjFS3h1N1sSMkcvvroWwjT5LQuGkGHu9JMAYs"
public = "vGKKAxVNfkSCdn8qh36nXdSZqyhPq644sQBoeZtcEUCR"

[keys.dh]
secret = "4hjtciEvuoFVT55nAzvdP9E76r18QwntWwFoeginCGnP"
public = "FHTJAk6oyt3jefEp1ZrPEn2MkqRt2LibEFd57AnEUZdb"

[keys.dkg]
secret = "ARtqWGmRWrBqZUr4MmiLaPgzjsiKp5USsC9iQNRMZYy4"
public = "7p1BtEz7WnFMt6Hr28X3Rngqza6i8hRoswhzZRFd6GzgkspLKHBfDocHP8DwzXiNiZ"

[chain]
id = 31337
rpc-url = "http://127.0.0.1:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
