stamp = "/tmp/timeboost.wzaREUZTT8gGNhtnHcdcqbrJVoEi8tQt8XLZyWDretYm.stamp"

[net]
bind = "127.0.0.1:8100"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "4Th9nd7dgUBKQUiTrVDxsd513W2r4PfyJv4YQbVPRnXx"
public = "wzaREUZTT8gGNhtnHcdcqbrJVoEi8tQt8XLZyWDretYm"

[keys.dh]
secret = "2HDMqk274Ed5dC3nEB4Fp9BHN7Njds9RD713TomP5ERj"
public = "Frmtaafy1HBFNCo2CNa5HuMK7psE3zeYn3io1FfUibKs"

[keys.dkg]
secret = "GcPfrWuoSGHf2E15oBjx55pSM3TSvV43Bg1DgFa1ukQH"
public = "6Zyn8o7Uws4Z9LAYH2C4P1fvkszEm9D65pJY5BSAUF5BxWRVGnwhDTYfwr8K3cXCcX"

[chain]
id = 31337
rpc-url = "http://127.0.0.1:8545/"
websocket-url = "ws://127.0.0.1:8545/"
key-management-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"
auction-contract = "0x1a642f0E3c3aF545E7AcBD38b07251B3990914F1"

[espresso]
namespace = 10101
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
