# Cleanup previous run:

[[step]]
[step.action]
kind  = "remove"
files = [
    "/tmp/timeboost.eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX.stamp",
    "/tmp/timeboost.vGKKAxVNfkSCdn8qh36nXdSZqyhPq644sQBoeZtcEUCR.stamp",
    "/tmp/timeboost.264jMLf85hfufg4ck97Hw2jiL6i1PHNoGUqxUqfhtssaE.stamp",
    "/tmp/timeboost.v6UBdLT5BvMhLW7iKv7M2xYeaW2SCAsnZ5PiSg6AaKfA.stamp",
    "/tmp/timeboost.tV66KknkDH47hRSNzwJtt7Q7EZtxVxQsNnUGoAJdDn6J.stamp"
]

# Start whole committee one by one:

[[step]]
[step.action]
kind = "start-node"
node = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"

[[step]]
[step.action]
kind = "start-node"
node = "vGKKAxVNfkSCdn8qh36nXdSZqyhPq644sQBoeZtcEUCR"

[[step]]
[step.action]
kind = "start-node"
node = "264jMLf85hfufg4ck97Hw2jiL6i1PHNoGUqxUqfhtssaE"

[[step]]
[step.action]
kind = "start-node"
node = "v6UBdLT5BvMhLW7iKv7M2xYeaW2SCAsnZ5PiSg6AaKfA"

[[step]]
[step.action]
kind = "start-node"
node = "tV66KknkDH47hRSNzwJtt7Q7EZtxVxQsNnUGoAJdDn6J"

# Stop and start one node:

[[step]]
delay = "+10s"
[step.action]
kind = "stop-node"
node = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"

[[step]]
delay = "+10s"
[step.action]
kind = "start-node"
node = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"
