# Start whole committee one by one:

[[step]]
action = {
    kind = "start-node",
    node = "21R4uDwS7fdxsNPWy92DArC575sYiQdEasFBVEpH8m53e"
}

[[step]]
action = {
    kind = "start-node",
    node = "23as9Uo6W2AeGronB6nMpcbs8Nxo6CoJ769uePw9sf6Ud"
}

[[step]]
action = {
    kind = "start-node",
    node = "23oAdU4acQbwSuC6aTEXqwkvQRVCjySzX18JfBNEbHgij"
}

[[step]]
action = {
    kind = "start-node",
    node = "29iGhwSi5p4zJn2XgGLCwWVU5rCw7aMM2Xk8aJnYnDweU"
}

[[step]]
action = {
    kind = "start-node",
    node = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"
}

# Stop and start one node:

[[step]]
delay  = "+10s"
action = {
    kind = "stop-node",
    node = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"
}

[[step]]
delay  = "+10s"
action = {
    kind = "start-node",
    node = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"
}
