# Start whole committee one by one:

[[step]]
[step.action]
kind = "start-node"
node = "21R4uDwS7fdxsNPWy92DArC575sYiQdEasFBVEpH8m53e"

[[step]]
[step.action]
kind = "start-node"
node = "23as9Uo6W2AeGronB6nMpcbs8Nxo6CoJ769uePw9sf6Ud"

[[step]]
[step.action]
kind = "start-node"
node = "23oAdU4acQbwSuC6aTEXqwkvQRVCjySzX18JfBNEbHgij"

[[step]]
[step.action]
kind = "start-node"
node = "29iGhwSi5p4zJn2XgGLCwWVU5rCw7aMM2Xk8aJnYnDweU"

[[step]]
[step.action]
kind = "start-node"
node = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"

# Stop and start all nodes one by one:

[[step]]
delay = "+10s"
[step.action]
kind = "stop-node"
node = "21R4uDwS7fdxsNPWy92DArC575sYiQdEasFBVEpH8m53e"

[[step]]
delay = "+10s"
[step.action]
kind = "start-node"
node = "21R4uDwS7fdxsNPWy92DArC575sYiQdEasFBVEpH8m53e"

[[step]]
delay = "+10s"
[step.action]
kind = "stop-node"
node = "23as9Uo6W2AeGronB6nMpcbs8Nxo6CoJ769uePw9sf6Ud"

[[step]]
delay = "+10s"
[step.action]
kind = "start-node"
node = "23as9Uo6W2AeGronB6nMpcbs8Nxo6CoJ769uePw9sf6Ud"

[[step]]
delay = "+10s"
[step.action]
kind = "stop-node"
node = "23oAdU4acQbwSuC6aTEXqwkvQRVCjySzX18JfBNEbHgij"

[[step]]
delay = "+10s"
[step.action]
kind = "start-node"
node = "23oAdU4acQbwSuC6aTEXqwkvQRVCjySzX18JfBNEbHgij"

[[step]]
delay = "+10s"
[step.action]
kind = "stop-node"
node = "29iGhwSi5p4zJn2XgGLCwWVU5rCw7aMM2Xk8aJnYnDweU"

[[step]]
delay = "+10s"
[step.action]
kind = "start-node"
node = "29iGhwSi5p4zJn2XgGLCwWVU5rCw7aMM2Xk8aJnYnDweU"

[[step]]
delay = "+10s"
[step.action]
kind = "stop-node"
node = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"

[[step]]
delay = "+10s"
[step.action]
kind = "start-node"
node = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"
