stamp = "/tmp/timeboost.21R4uDwS7fdxsNPWy92DArC575sYiQdEasFBVEpH8m53e.stamp"

[net]
bind = "0.0.0.0:8000"
nitro = "nitro2:55000"

[keys.signing]
secret = "Fg3tVVbB4UX5cTcqicFkk1ApbUJ71zq9m86ffiBHerTn"
public = "21R4uDwS7fdxsNPWy92DArC575sYiQdEasFBVEpH8m53e"

[keys.dh]
secret = "221uwQa7dhYyzwwVQcBF4TAkmyjEcZ5egbrtUN5P3uKq"
public = "DRYKr9pHPf6i6QmQiAihrQnEqEYXg96fe5kyMiCrBUJP"

[keys.dkg]
secret = "4egxEWyRd5SEG3hoDuCcon1z822oFEXeiEdjnn4VgFyN"
public = "6Uzern4hX1a2VJmWmHMavmUgeXmNDrxsC4JpCRB49dXk7tRK5QwXtuTUw8sUpGpGkc"

[chain]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 412346
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
