stamp = "/tmp/timeboost.23oAdU4acQbwSuC6aTEXqwkvQRVCjySzX18JfBNEbHgij.stamp"

[net]
bind = "0.0.0.0:8000"
nitro = "nitro6:55000"

[keys.signing]
secret = "3w2vnSTfFsWXeNfRhS9TfZm5rptKmdgZPQUAvb2PaqRU"
public = "23oAdU4acQbwSuC6aTEXqwkvQRVCjySzX18JfBNEbHgij"

[keys.dh]
secret = "H7ifD5bqkEdPbHTss5VHfZ64jTQr9si6WsgTxvMQAphA"
public = "B65CLdoYGSRtXRR4YU2wqzpqrwcd4KHiQqgaW5ShnoY6"

[keys.dkg]
secret = "5Fwo9VHphxfWK3vT5zTWsKaZRzXSgHYn3XZL5rQdRU4s"
public = "7KgCqy1taizFPX2v5CvZit8HDnNPQF2M7EbHHy24a3banaKkqeqye6kM4apnbjZMhd"

[chain]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 412346
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
