stamp = "/tmp/timeboost.264jMLf85hfufg4ck97Hw2jiL6i1PHNoGUqxUqfhtssaE.stamp"

[net]
bind = "0.0.0.0:8000"
nitro = "nitro2:55000"

[keys.signing]
secret = "2yWTaC6MWvNva97t81cd9QX5qph68NnB1wRVwAChtuGr"
public = "264jMLf85hfufg4ck97Hw2jiL6i1PHNoGUqxUqfhtssaE"

[keys.dh]
secret = "Fo2nYV4gE9VfoVW9bSySAJ1ZuKT461x6ovZnr3EecCZg"
public = "63eYNKoW2PsWZFhHHj3eZwHTdPE7gEjEDM7gGeDf9Uaj"

[keys.dkg]
secret = "77r7T3En7NNQvRA81G5hLhJD3VpnigJdkPonX3oAwWkX"
public = "62bnAAbU58zZUcGqy9JKGZRZHkm3g7JZB2DtJGQyChXQBPGvXSS6fF21yoxiVuD1eb"

[chain]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 412346
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
