stamp = "/tmp/timeboost.h7qA6fzJMhYLotwxNRGGBEDqUkaNpCJ8cBeCGQuAumTq.stamp"

[net]
bind = "0.0.0.0:8000"
nitro = "nitro5:55000"

[keys.signing]
secret = "8rNjkteTcKonpHTGoQYNihfkd7YgAfWRixLKTXatsLq9"
public = "h7qA6fzJMhYLotwxNRGGBEDqUkaNpCJ8cBeCGQuAumTq"

[keys.dh]
secret = "DTYobbJujfpvhLSyEWe5AmqEb22LwzJoHPNhLVaRXcBK"
public = "HXD3TRTQ2cK8oGbEWmhnRdwFa96wBPc1mntVt7wt98mK"

[keys.dkg]
secret = "7zEj9Tq2NjbUeMoqLMYBwjmTwjUMoVTFkqztfL9TdHmN"
public = "78HGPt9ceH5TMn5rB9LUdxkY9pofXE8RPo4WckmyqSicnweQ4Ue5DJ6dTDQ1ptLwfz"

[chain]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 412346
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
