stamp = "/tmp/timeboost.mjL4pJF2jqy4TAht8UveAF9H7xUYYyP16aDH6Rnu8Zi8.stamp"

[net]
bind = "0.0.0.0:8000"
nitro = "nitro13:55000"

[keys.signing]
secret = "8ctic7ZqgQ8VP5U9DKNDcemyM4CmzFsGsJduqPekfcwj"
public = "mjL4pJF2jqy4TAht8UveAF9H7xUYYyP16aDH6Rnu8Zi8"

[keys.dh]
secret = "HgTF9vgrnua9xWhspKiDE9vQGuzyhmGMQJY2JFnD2hrY"
public = "EJ3ZpDXbmD9Ma1rRLY8LVGuNGjiskuGmnyzNZWXyQvRa"

[keys.dkg]
secret = "9aVdLRQM4sYKeXHqt6kNALFQyvAUQ9tXDnwMtwtzHie2"
public = "5kA6kUeAuqVYRcUugGkngV2DJSpDDJTxzGmZdiNEsWonp5yW9oYLNJQB3n6Niyw6PW"

[chain]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 412346
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
