stamp = "/tmp/timeboost.o5HJvYeQHUn28Y2149t1CLZeMfK6gqWf62BtErxghPvD.stamp"

[net]
bind = "0.0.0.0:8000"
nitro = "nitro7:55000"

[keys.signing]
secret = "6PnUNhm6FLR4GLVqDFeAg5w5zphs7N5H9tteT5xzECmn"
public = "o5HJvYeQHUn28Y2149t1CLZeMfK6gqWf62BtErxghPvD"

[keys.dh]
secret = "D4waADmJvkcedwhpN9P7w5g79Y7RR1ibYbgkkY62D6Vm"
public = "3iJpaEKb3Zuo3mRgFYXayytr22TmroANnx98UfmrPNG7"

[keys.dkg]
secret = "6eB7gVuwt3WgNewWrMLmpuhcG9qzF1cDE95UevBCgoXx"
public = "7MQbJw5poGYjx3QE1c6tXpNcKGErJWCJXga9aqeE3iNcKb8tu6jaQZ4P8b7NHAe7pd"

[chain]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 412346
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
