stamp = "/tmp/timeboost.pG9cBbvmj7qqCAVKR9EKefwYrHX8c4y1go891CVCPw1W.stamp"

[net]
bind = "0.0.0.0:8000"
nitro = "nitro11:55000"

[keys.signing]
secret = "5N8kSoP4zvGo4TfZxWHQMTbthcWFSehPCPueQbZxKRBD"
public = "pG9cBbvmj7qqCAVKR9EKefwYrHX8c4y1go891CVCPw1W"

[keys.dh]
secret = "4gyBDPfxePdhKSZpRQCpA97VobTg3wiUhzYAGtTfVhXS"
public = "BPuD53onChfNdaAQkkqeKDWj2RvmJywoMehuamSBidSx"

[keys.dkg]
secret = "CC6bf85AB7Jjbtdzt5bZ2D3f5evJdV4Edkmih6ZPE8tt"
public = "5uz43rVdxMeLPoRtgAY74NuALzv7XoCzPSyeNpfopaev4HWtA17B7wWHFxkL8zHfzv"

[chain]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 412346
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
