stamp = "/tmp/timeboost.tiLaXi4xvFAK2GcUdjbDxWpJKq3kceqgJXTkKjGhduEJ.stamp"

[net]
bind = "0.0.0.0:8000"
nitro = "nitro14:55000"

[keys.signing]
secret = "53X3PTCYNNc3FsSiJX1GCDxPmw3k4sfh4jVSF8pR45z"
public = "tiLaXi4xvFAK2GcUdjbDxWpJKq3kceqgJXTkKjGhduEJ"

[keys.dh]
secret = "4zMVo2A4ZfqF2pymNz3xPMJjoMWitVywrTntdgGyL4UU"
public = "2179bYS7qukTLacc3Wz5mS5oFJnUKzNmrFAMwwUGn7B5"

[keys.dkg]
secret = "9m2Ugq6mqKcCdjxXXoai2XRxt7hq48p2tmpnGstUR5Zr"
public = "6MFv9guPANDGQ9gnzXhWdPW29nTsYqXodgtE1hV7JhDjSRjiuaM4AESb4uW2Pc74DR"

[chain]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 412346
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
