stamp = "/tmp/timeboost.tV66KknkDH47hRSNzwJtt7Q7EZtxVxQsNnUGoAJdDn6J.stamp"

[net]
bind = "0.0.0.0:8000"
nitro = "nitro4:55000"

[keys.signing]
secret = "6LMMEuoPRCkpDsnxnANCRCBC6JagdCHs2pjNicdmQpQE"
public = "tV66KknkDH47hRSNzwJtt7Q7EZtxVxQsNnUGoAJdDn6J"

[keys.dh]
secret = "39wAn3bQzpn19oa8CiaNUFd8GekQAJMMuzrbp8Jt3FKz"
public = "HXaesvEGFiDgrVTix1fKzSLTarFexTZSJD6ymSrF7vPL"

[keys.dkg]
secret = "GFvv2wcQmiGpk5rFp1FGpeUjnVUyZmGM9k8VHb1Jn7EG"
public = "6R69TzDg3jo1MTex9Uter9XQud458YPpSvXirkYdS295PV81CRvgz5jVWQbkCpZnYV"

[chain]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 412346
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
