stamp = "/tmp/timeboost.wzaREUZTT8gGNhtnHcdcqbrJVoEi8tQt8XLZyWDretYm.stamp"

[net]
bind = "0.0.0.0:8000"
nitro = "nitro10:55000"

[keys.signing]
secret = "4Th9nd7dgUBKQUiTrVDxsd513W2r4PfyJv4YQbVPRnXx"
public = "wzaREUZTT8gGNhtnHcdcqbrJVoEi8tQt8XLZyWDretYm"

[keys.dh]
secret = "2HDMqk274Ed5dC3nEB4Fp9BHN7Njds9RD713TomP5ERj"
public = "Frmtaafy1HBFNCo2CNa5HuMK7psE3zeYn3io1FfUibKs"

[keys.dkg]
secret = "GcPfrWuoSGHf2E15oBjx55pSM3TSvV43Bg1DgFa1ukQH"
public = "6Zyn8o7Uws4Z9LAYH2C4P1fvkszEm9D65pJY5BSAUF5BxWRVGnwhDTYfwr8K3cXCcX"

[chain]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
inbox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
inbox-block-tag = "finalized"

[espresso]
namespace = 412346
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
