
global:
  scrape_interval: 1s

scrape_configs:
- job_name: status
  static_configs:
    - targets:
      - node0:8004
      - node1:8004
      - node2:8004
      - node3:8004
  metrics_path: /i/metrics
- job_name: cloud_status
  static_configs:
    - targets:
      - timeboost-lb-50d346419d44f480.elb.us-east-2.amazonaws.com:9000
      - timeboost-lb-50d346419d44f480.elb.us-east-2.amazonaws.com:9001
      - timeboost-lb-50d346419d44f480.elb.us-east-2.amazonaws.com:9002
      - timeboost-lb-50d346419d44f480.elb.us-east-2.amazonaws.com:9003
      - timeboost-lb-0d364c185da81754.elb.us-west-2.amazonaws.com:9004
      - timeboost-lb-0d364c185da81754.elb.us-west-2.amazonaws.com:9005
      - timeboost-lb-0d364c185da81754.elb.us-west-2.amazonaws.com:9006
      - timeboost-lb-0d364c185da81754.elb.us-west-2.amazonaws.com:9007
      - timeboost-lb-db5c0565e599345e.elb.eu-north-1.amazonaws.com:9008
      - timeboost-lb-db5c0565e599345e.elb.eu-north-1.amazonaws.com:9009
      - timeboost-lb-db5c0565e599345e.elb.eu-north-1.amazonaws.com:9010
      - timeboost-lb-db5c0565e599345e.elb.eu-north-1.amazonaws.com:9011
      - timeboost-lb-2ac74543b8da9a68.elb.ap-northeast-1.amazonaws.com:9012
      - timeboost-lb-2ac74543b8da9a68.elb.ap-northeast-1.amazonaws.com:9013
      - timeboost-lb-2ac74543b8da9a68.elb.ap-northeast-1.amazonaws.com:9014
      - timeboost-lb-2ac74543b8da9a68.elb.ap-northeast-1.amazonaws.com:9015
      - timeboost-lb-58994ad767e6f67b.elb.ap-southeast-2.amazonaws.com:9016
      - timeboost-lb-58994ad767e6f67b.elb.ap-southeast-2.amazonaws.com:9017
      - timeboost-lb-58994ad767e6f67b.elb.ap-southeast-2.amazonaws.com:9018
      - timeboost-lb-58994ad767e6f67b.elb.ap-southeast-2.amazonaws.com:9019
  metrics_path: /v0/status/metrics
