
global:
  scrape_interval: 1s

scrape_configs:
- job_name: status
  static_configs:
    - targets:
      - node0:8004
      - node1:8004
      - node2:8004
      - node3:8004
  metrics_path: /i/metrics
