[[committee]]
id    = 0
start = "2025-10-01T00:00:00Z"

[[committee.member]]
config = "test-configs/docker/21R4uDwS7fdxsNPWy92DArC575sYiQdEasFBVEpH8m53e.public.toml"

[[committee.member]]
config = "test-configs/docker/23as9Uo6W2AeGronB6nMpcbs8Nxo6CoJ769uePw9sf6Ud.public.toml"

[[committee.member]]
config = "test-configs/docker/23oAdU4acQbwSuC6aTEXqwkvQRVCjySzX18JfBNEbHgij.public.toml"

[[committee.member]]
config = "test-configs/docker/29iGhwSi5p4zJn2XgGLCwWVU5rCw7aMM2Xk8aJnYnDweU.public.toml"

[[committee.member]]
config = "test-configs/docker/eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX.public.toml"
