index = 0
rpc-url = "http://127.0.0.1:8545"
contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[committee]
id = 0
start = "2025-10-01T00:00:00Z"

[[committee.member]]
config = "test-configs/nodes/264jMLf85hfufg4ck97Hw2jiL6i1PHNoGUqxUqfhtssaE.public.toml"

[[committee.member]]
config = "test-configs/nodes/eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX.public.toml"

[[committee.member]]
config = "test-configs/nodes/tV66KknkDH47hRSNzwJtt7Q7EZtxVxQsNnUGoAJdDn6J.public.toml"

[[committee.member]]
config = "test-configs/nodes/v6UBdLT5BvMhLW7iKv7M2xYeaW2SCAsnZ5PiSg6AaKfA.public.toml"

[[committee.member]]
config = "test-configs/nodes/vGKKAxVNfkSCdn8qh36nXdSZqyhPq644sQBoeZtcEUCR.public.toml"
