committee = 0
stamp = "/tmp/timeboost.0.stamp"

[net]
bind = "0.0.0.0:8000"
nitro = "localhost:55000"

[keys.signing]
secret = "3hzb3bRzn3dXSV1iEVE6mU4BF2aS725s8AboRxLwULPp"
public = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"

[keys.dh]
secret = "BB3zUfFQGfw3sL6bpp1JH1HozK6ehEDmRGoiCpQH62rZ"
public = "AZrLbV37HAGhBWh49JHzup6Wfpu2AAGWGJJnxCDJibiY"

[keys.dkg]
secret = "BW8gq8MARtDkSJL6daobPtGQm22TKkXdbLNrNGngNGTB"
public = "7PdmfTS45d2hTXB8NcrTmvDwUVBimpYBbrBaGnu3i5Ne65krVfUpbe7bYRHS3AEg7H"

[chain]
namespace = 412346

[chain.parent]
id = 1337
rpc-url = "http://127.0.0.1:8545/"
ws-url = "ws://127.0.0.1:8546/"
ibox-contract = "0xcbfd7eeb1cbd827a8b4de3752d3994e9a8641fa2"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "http://127.0.0.1:41000/v1/"
websockets-base-url = "ws://127.0.0.1:41000/v1/"
max-transaction-size = 1048576
