committee = 0
stamp = "/tmp/timeboost.0.stamp"

[net.public]
address = "127.0.0.1:8000"
http-api = "127.0.0.1:8004"
batch-poster-api = "http://host.docker.internal:8547"

[net.internal]
address = "0.0.0.0:8003"
nitro = "localhost:55000"

[keys.signing]
secret = "3hzb3bRzn3dXSV1iEVE6mU4BF2aS725s8AboRxLwULPp"
public = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"

[keys.dh]
secret = "BB3zUfFQGfw3sL6bpp1JH1HozK6ehEDmRGoiCpQH62rZ"
public = "AZrLbV37HAGhBWh49JHzup6Wfpu2AAGWGJJnxCDJibiY"

[keys.dkg]
secret = "BW8gq8MARtDkSJL6daobPtGQm22TKkXdbLNrNGngNGTB"
public = "7PdmfTS45d2hTXB8NcrTmvDwUVBimpYBbrBaGnu3i5Ne65krVfUpbe7bYRHS3AEg7H"

[chain]
namespace = 412346

[chain.parent]
id = 1337
rpc-url = "http://127.0.0.1:8545/"
ws-url = "ws://127.0.0.1:8546/"
ibox-contract = "0x1f5aeb9665838a116ac5be48c36aa7c87eefb386"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "http://127.0.0.1:41000/v1/"
websockets-base-url = "ws://127.0.0.1:41000/v1/"
max-transaction-size = 1048576
