committee = 0
stamp = "/tmp/timeboost.1.stamp"

<<<<<<< HEAD
[net.public]
address = "127.0.0.1:8010"
http-api = "127.0.0.1:8014"
batch-poster-api = "http://host.docker.internal:8557"

[net.internal]
address = "0.0.0.0:8013"
=======
[net]
bind = "0.0.0.0:8010"
>>>>>>> origin/main
nitro = "localhost:55010"

[keys.signing]
secret = "FWJzNGvEjFS3h1N1sSMkcvvroWwjT5LQuGkGHu9JMAYs"
public = "vGKKAxVNfkSCdn8qh36nXdSZqyhPq644sQBoeZtcEUCR"

[keys.dh]
secret = "4hjtciEvuoFVT55nAzvdP9E76r18QwntWwFoeginCGnP"
public = "FHTJAk6oyt3jefEp1ZrPEn2MkqRt2LibEFd57AnEUZdb"

[keys.dkg]
secret = "ARtqWGmRWrBqZUr4MmiLaPgzjsiKp5USsC9iQNRMZYy4"
public = "7p1BtEz7WnFMt6Hr28X3Rngqza6i8hRoswhzZRFd6GzgkspLKHBfDocHP8DwzXiNiZ"

[chain]
namespace = 412346

[chain.parent]
id = 1337
rpc-url = "http://127.0.0.1:8545/"
ws-url = "ws://127.0.0.1:8546/"
ibox-contract = "0x1f5aeb9665838a116ac5be48c36aa7c87eefb386"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "http://127.0.0.1:41000/v1/"
websockets-base-url = "ws://127.0.0.1:41000/v1/"
max-transaction-size = 1048576
