name: Release Timeboost AMI

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ami:
    runs-on: ubuntu-latest
    env:
      AWS_PROFILE: timeboost-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install nightly rustfmt
        run: rustup component add --toolchain nightly rustfmt

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Build AMI
        run: |
          cd packer/tx-generator
          just init
          just build
          just make-overlay
          VERSION=${GITHUB_REF_NAME} just make-image
