on:
  push:
    branches:
      - "*"
    tags:
      # Match tags in the format YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.docker.outputs.digest }}
    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Repo
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Need this to build containers in CI
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Build and push the images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/metadata-action@v5
        name: Generate Docker Metadata
        id: meta
        with:
          images: ghcr.io/espressosystems/timeboost/geth-l1
          flavor: |
            latest=true
            suffix=-amd64,onlatest=true

      - name: Build and push Geth L1 Docker image
        uses: docker/build-push-action@v6
        id: docker
        with:
          context: .
          build-args: NITRO_CONTRACTS_BRANCH=v3.1.0
          file: ./docker/geth-l1.Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-arm:
    runs-on: ubuntu-24.04-arm
    outputs:
      digest: ${{ steps.docker.outputs.digest }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Docker BuildKit (buildx)
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Repo
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        name: Generate Docker Metadata
        id: meta
        with:
          images: ghcr.io/espressosystems/timeboost/geth-l1
          flavor: |
            latest=true
            suffix=-arm64,onlatest=true

      - name: Build and push Geth L1 Docker image
        uses: docker/build-push-action@v6
        id: docker
        with:
          context: .
          build-args: NITRO_CONTRACTS_BRANCH=v3.1.0
          file: ./docker/geth-l1.Dockerfile
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  merge:
    runs-on: ubuntu-latest
    needs: [build, build-arm]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker BuildKit (buildx)
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Repo
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Geth L1 Docker image
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/espressosystems/timeboost/geth-l1
          flavor: |
            latest=true

      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@master
        with:
            tags: ghcr.io/espressosystems/timeboost/geth-l1:${{steps.metadata.outputs.version}}
            inputs: ghcr.io/espressosystems/timeboost/geth-l1@${{needs.build.outputs.digest}},ghcr.io/espressosystems/timeboost/geth-l1@${{needs.build-arm.outputs.digest}}
            push: ${{ github.event_name != 'pull_request' }}

      - name: Create and push manifest images to latest
        uses: Noelware/docker-manifest-action@master
        with:
            tags: ghcr.io/espressosystems/timeboost/geth-l1:latest
            inputs: ghcr.io/espressosystems/timeboost/geth-l1@${{needs.build.outputs.digest}},ghcr.io/espressosystems/timeboost/geth-l1@${{needs.build-arm.outputs.digest}}
            push: ${{ github.event_name != 'pull_request' }}